---
baseurl: "/enterprise/"
languageCode: "en-us"
title: "Camunda Enterprise"
theme: "camunda"

blackfriday:
  plainIdAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
  section:
    id: "enterprise"
  github:
    repositoryName: "camunda/camunda-docs-static"
    branch: "master/enterprise"
...
