---
baseurl: "http://stage.docs.camunda.org/get-started/"
languageCode: "en-us"
title: "Getting started with Camunda BPM"
theme: "camunda"

blackfriday:
  plainIdAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "http://stage.docs.camunda.org/get-started/"
    - id: "manual"
      name: "Manual"
      url: "http://stage.docs.camunda.org/"
    - id: "enterprise"
      name: "Enterprise"
      url: "http://stage.docs.camunda.org/enterprise"
  section:
    id: "get-started"
  github:
    repositoryName: "camunda/camunda-docs-static"
    branch: "master"
...
