---
baseurl: "/optimize/"
languageCode: "en-us"
title: "Camunda Optimize"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "BPM Platform"
      url: "/manual"
    - id: "optimize"
      name: "Optimize"
      url: "/optimize"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
  section:
    id: "optimize"
    version: "develop"
    versionAlias: "2.0"
    versions:
      - "1.5"
      - "develop"
  github:
    repositoryName: "camunda/camunda-docs-static"
    branch: "master/optimize"
...
